name: medical-emergency-coordination-system

services:
  kafka:
    image: apache/kafka:3.7.0
    ports:
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 10

  emergency-db:
    image: postgres:17-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: emergency_request_db
      POSTGRES_USER: medical
      POSTGRES_PASSWORD: medical
    volumes:
      - emergency-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U medical -d emergency_request_db"]
      interval: 10s
      timeout: 5s
      retries: 10

  ambulance-db:
    image: postgres:17-alpine
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: ambulance_service
      POSTGRES_USER: medical
      POSTGRES_PASSWORD: medical
    volumes:
      - ambulance-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U medical -d ambulance_service"]
      interval: 10s
      timeout: 5s
      retries: 10

  hospital-db:
    image: postgres:17-alpine
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: hospital_db
      POSTGRES_USER: medical
      POSTGRES_PASSWORD: medical
    volumes:
      - hospital-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U medical -d hospital_db" ]
      interval: 10s
      timeout: 5s
      retries: 10

  case-db:
    image: postgres:17-alpine
    ports:
      - "5439:5432"
    environment:
      POSTGRES_DB: case_db
      POSTGRES_USER: medical
      POSTGRES_PASSWORD: medical
    volumes:
      - case-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U medical -d case_db" ]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  emergency-db-data:
  ambulance-db-data:
  hospital-db-data:
  case-db-data:
