### Get available hospitals
GET http://localhost:8086/hospitals?minBeds=1
Accept: application/json

### Reserve a bed (Replace UUID with AIIMS from the GET request)
PATCH http://localhost:8086/hospitals/8809c91b-ec22-4a8e-8ae1-03bc93385de1/reserve-bed