### ==========================================
### 0. SETUP: CREATE OUR USERS
### ==========================================

### Create Dispatcher
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "name": "Dave Dispatcher",
  "email": "dispatcher@mediflow.com",
  "password": "password123",
  "role": "DISPATCHER"
}

### Create Paramedic
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "name": "Pam Paramedic",
  "email": "paramedic@mediflow.com",
  "password": "password123",
  "role": "PARAMEDIC"
}

### Create Admin
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "name": "Alice Admin",
  "email": "admin@mediflow.com",
  "password": "adminpassword",
  "role": "ADMIN"
}




### ==========================================
### SCENARIO 1: Valid Dispatcher Creates Emergency
### ==========================================

### 1A. Login as Dispatcher (Copy the token from the response!)
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "dispatcher@mediflow.com",
  "password": "password123"
}

### 1B. Create Emergency (Paste token below)
POST http://localhost:8080/api/emergency
Content-Type: application/json
Idempotency-Key: {{$uuid}}
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlIjoiRElTUEFUQ0hFUiIsInN1YiI6IjEiLCJpYXQiOjE3ODE1MDAwMDAsImV4cCI6MTc4MTU4NjQwMH0.wk7QYQwcWxVPa_zN0cgnk7HXwMcWGku9Y2pjp8SypE5Bl-na5_yxT4o7cOp7aKvd

{
  "patientId": "PAT-98765",
  "severity": "CRITICAL",
  "latitude": 28.6139,
  "longitude": 77.2090
}

### ==========================================
### SCENARIO 2: Invalid JWT is Rejected
### ==========================================

### 2A. Attempt request with fake token
POST http://localhost:8080/api/emergency
Content-Type: application/json
Idempotency-Key: 123765
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.fake.token

### EXPECTED: 401 Unauthorized


### ==========================================
### SCENARIO 3: Paramedic Cannot Create Hospital
### ==========================================

### 3A. Login as Paramedic (Copy the token!)
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "paramedic@mediflow.com",
  "password": "password123"
}

### 3B. Attempt to access a restricted Admin endpoint
POST http://localhost:8080/api/hospitals
Content-Type: application/json
Idempotency-Key: 2398736
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlIjoiUEFSQU1FRElDIiwic3ViIjoiMiIsImlhdCI6MTc4MTAxMjI2MiwiZXhwIjoxNzgxMDk4NjYyfQ.GsFh9Dc1fEuu_ycUtey6rz6U32C6bAEP-58oRtgWtFPxxSXU31r6SMpessMEuelH

{
  "name": "City General",
  "totalBeds": 150,
  "latitude": 28.6139,
  "longitude": 77.2090
}

### EXPECTED: 403 Forbidden


### ==========================================
### SCENARIO 4: Admin Creates Hospital
### ==========================================

### 4A. Login as Admin (Copy the token!)
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "admin@mediflow.com",
  "password": "adminpassword"
}

### 4B. Admin accesses restricted endpoint
POST http://localhost:8080/api/hospitals
Content-Type: application/json
Idempotency-Key: 234546
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlIjoiQURNSU4iLCJzdWIiOiIxIiwiaWF0IjoxNzgxMDEyMzA2LCJleHAiOjE3ODEwOTg3MDZ9.RFv_IOq1xpUlH2_wau0DULRwtsogMhcfihCgskKb7Tp46p7j1cGIGmVFDPh-Px3t

{
  "name": "City General",
  "totalBeds": 150,
  "latitude": 28.6139,
  "longitude": 77.2090
}

### EXPECTED: 201 Created

### ==========================================
### ADD A NEW AMBULANCE
### ==========================================

### Add Advanced Life Support Ambulance
POST http://localhost:8080/api/ambulances
Content-Type: application/json
Idempotency-Key: {{$uuid}}
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlIjoiQURNSU4iLCJzdWIiOiIyIiwiaWF0IjoxNzgxNDk5OTM0LCJleHAiOjE3ODE1ODYzMzR9._8ltUwEV3Ekl5MeEUnhz7Sxkv8PnDJYRn1cThAkeqJbCqvU0agXTshtcO4XO-vc6

{
  "registrationNumber": "DL-1C-AA-1123",
  "capabilities": "ALS, Ventilator, Defibrillator",
  "crewInfo": "2 Paramedics, 1 Driver"
}

### ==========================================
### ADD A NEW HOSPITAL
### ==========================================

### Admin accesses restricted endpoint using proper DTO payload
POST http://localhost:8080/api/hospitals
Content-Type: application/json
Idempotency-Key: {{$uuid}}
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlIjoiQURNSU4iLCJzdWIiOiIyIiwiaWF0IjoxNzgxNDk5OTM0LCJleHAiOjE3ODE1ODYzMzR9._8ltUwEV3Ekl5MeEUnhz7Sxkv8PnDJYRn1cThAkeqJbCqvU0agXTshtcO4XO-vc6

{
  "hospitalName": "Apollo Downtown 5",
  "availableBeds": 250,
  "latitude": 28.6150,
  "longitude": 77.2100
}